// color from "http://www.flatcolorsui.com/"
export const firstSnakeHeadColor = "#2ecc71"; // G5
export const firstSnakeEyePrimaryColor = "#2ecc71"; // G5
export const firstSnakeEyeSecondaryColor = "#f1f2f6";
export const firstSnakeEyeTertiaryColor = "#005c01"; // G12
export const firstSnakeNostrilColor = "#005c01"; // G12
export const firstSnakeBodyColor = "#0eac51"; // G7
export const firstSnakeLongStainColor = "#2ecc71"; // G5
export const firstSnakeRoundStainColor = "#1ebc61"; // G6
export const firstSnakeTailColor = "#2ecc71"; // G5
export const firstSnakeTailStainColorRightDirection = "8effc1"; // G1
export const firstSnakeTailStainColorLeftDirection = "#5efca1"; // G2
export const firstSnakeTailStainColorTopDirection = "#4eec91"; // G3
export const firstSnakeTailStainColorBottomDirection = "#3edc81"; // G4
export const firstSnakeBorderColor = "#1ebc61"; // G6
export const firstSnakeStainBorderColor = "#008c31"; // G9

export const secondSnakeHeadColor = "#ff6c5c"; // B5
export const secondSnakeEyePrimaryColor = "#ff6c5c"; // B5
export const secondSnakeEyeSecondaryColor = "#f1f2f6";
export const secondSnakeEyeTertiaryColor = "#870000"; // B12
export const secondSnakeNostrilColor = "#870000"; // B12
export const secondSnakeBodyColor = "#e74c3c"; // B7
export const secondSnakeLongStainColor = "#ff6c5c"; // B5
export const secondSnakeRoundStainColor = "#f75c4c"; // B6
export const secondSnakeTailColor = "#ff6c5c"; // B5
export const secondSnakeTailStainColorRightDirection = "#ffccbc"; // B1
export const secondSnakeTailStainColorLeftDirection = "#ffac9c"; // B2
export const secondSnakeTailStainColorTopDirection = "#ff8c7c"; // B3
export const secondSnakeTailStainColorBottomDirection = "#ff7c6c"; // B4
export const secondSnakeBorderColor = "#f75c4c"; // B6
export const secondSnakeStainBorderColor = "#c72c1c"; // B9

export const thirdSnakeHeadColor = "#fa5c98"; // C5
export const thirdSnakeEyePrimaryColor = "#fa5c98"; // C5
export const thirdSnakeEyeSecondaryColor = "#f1f2f6";
export const thirdSnakeEyeTertiaryColor = "#8a0028"; // C12
export const thirdSnakeNostrilColor = "#8a0028"; // C12
export const thirdSnakeBodyColor = "#da3c78"; // C7
export const thirdSnakeLongStainColor = "#fa5c98"; // C5
export const thirdSnakeRoundStainColor = "#ea4c88"; // C6
export const thirdSnakeTailColor = "#fa5c98"; // C5
export const thirdSnakeTailStainColorRightDirection = "#ffbcd8"; // C1
export const thirdSnakeTailStainColorLeftDirection = "#ff8cc8"; // C2
export const thirdSnakeTailStainColorTopDirection = "#ff7cb8"; // C3
export const thirdSnakeTailStainColorBottomDirection = "#ff6ca8"; // C4
export const thirdSnakeBorderColor = "#ea4c88"; // C6
export const thirdSnakeStainBorderColor = "#ba1c58"; // C9

export const fourthSnakeHeadColor = "#9b59b6"; // D5
export const fourthSnakeEyePrimaryColor = "#9b59b6"; // D5
export const fourthSnakeEyeSecondaryColor = "#f1f2f6";
export const fourthSnakeEyeTertiaryColor = "#1e003d"; // D12
export const fourthSnakeNostrilColor = "#1e003d"; // D12
export const fourthSnakeBodyColor = "#7e349d"; // D7
export const fourthSnakeLongStainColor = "#9b59b6"; // D5
export const fourthSnakeRoundStainColor = "#8e44ad"; // D6
export const fourthSnakeTailColor = "#9b59b6"; // D5
export const fourthSnakeTailStainColorRightDirection = "#dcc6e0"; // D1
export const fourthSnakeTailStainColorLeftDirection = "#cea0e4"; // D2
export const fourthSnakeTailStainColorTopDirection = "#be90d4"; // D3
export const fourthSnakeTailStainColorBottomDirection = "#ab69c6"; // D4
export const fourthSnakeBorderColor = "#8e44ad"; // D6
export const fourthSnakeStainBorderColor = "#5e147d"; // D9

export const fifthSnakeHeadColor = "#1297e0"; // E5
export const fifthSnakeEyePrimaryColor = "#1297e0"; // E5
export const fifthSnakeEyeSecondaryColor = "#f1f2f6";
export const fifthSnakeEyeTertiaryColor = "#102770"; // E12
export const fifthSnakeNostrilColor = "#102770"; // E12
export const fifthSnakeBodyColor = "#0077c0"; // E7
export const fifthSnakeLongStainColor = "#1297e0"; // E5
export const fifthSnakeRoundStainColor = "#0287d0"; // E6
export const fifthSnakeTailColor = "#1297e0"; // E5
export const fifthSnakeTailStainColorRightDirection = "#39d5ff"; // E1
export const fifthSnakeTailStainColorLeftDirection = "#29c5ff"; // E2
export const fifthSnakeTailStainColorTopDirection = "#19b5fe"; // E3
export const fifthSnakeTailStainColorBottomDirection = "#22a7f0"; // E4
export const fifthSnakeBorderColor = "#0287d0"; // E6
export const fifthSnakeStainBorderColor = "#0057a0"; // E9

export const sixthSnakeHeadColor = "#27cbc0"; // F5
export const sixthSnakeEyePrimaryColor = "#27cbc0"; // F5
export const sixthSnakeEyeSecondaryColor = "#f1f2f6";
export const sixthSnakeEyeTertiaryColor = "#005b50"; // F12
export const sixthSnakeNostrilColor = "#005b50"; // F12
export const sixthSnakeBodyColor = "#07aba0"; // F7
export const sixthSnakeLongStainColor = "#27cbc0"; // F5
export const sixthSnakeRoundStainColor = "#17bbb0"; // F6
export const sixthSnakeTailColor = "#27cbc0"; // F5
export const sixthSnakeTailStainColorRightDirection = "#5efaf7"; // F1
export const sixthSnakeTailStainColorLeftDirection = "#51f5ea"; // F2
export const sixthSnakeTailStainColorTopDirection = "#47ebe0"; // F3
export const sixthSnakeTailStainColorBottomDirection = "#37dbd0"; // F4
export const sixthSnakeBorderColor = "#17bbb0"; // F6
export const sixthSnakeStainBorderColor = "#008b80"; // F9

export const seventhSnakeHeadColor = "#f5ab35"; // H5
export const seventhSnakeEyePrimaryColor = "#f5ab35"; // H5
export const seventhSnakeEyeSecondaryColor = "#f1f2f6";
export const seventhSnakeEyeTertiaryColor = "#a84410"; // H12
export const seventhSnakeNostrilColor = "#a84410"; // H12
export const seventhSnakeBodyColor = "#f1892d"; // H7
export const seventhSnakeLongStainColor = "#f5ab35"; // H5
export const seventhSnakeRoundStainColor = "#f39c12"; // H6
export const seventhSnakeTailColor = "#f5ab35"; // H5
export const seventhSnakeTailStainColorRightDirection = "#fde3a7"; // H1
export const seventhSnakeTailStainColorLeftDirection = "#ffcf4b"; // H2
export const seventhSnakeTailStainColorTopDirection = "#f9bf3b"; // H3
export const seventhSnakeTailStainColorBottomDirection = "#f9b32f"; // H4
export const seventhSnakeBorderColor = "#f39c12"; // H6
export const seventhSnakeStainBorderColor = "#d87400"; // H9

export const eighthSnakeHeadColor = "#ff926b"; // I5
export const eighthSnakeEyePrimaryColor = "#ff926b"; // I5
export const eighthSnakeEyeSecondaryColor = "#f1f2f6";
export const eighthSnakeEyeTertiaryColor = "#932210"; // I12
export const eighthSnakeNostrilColor = "#932210"; // I12
export const eighthSnakeBodyColor = "#e3724b"; // I7
export const eighthSnakeLongStainColor = "#ff926b"; // I5
export const eighthSnakeRoundStainColor = "#f3825b"; // I6
export const eighthSnakeTailColor = "#ff926b"; // I5
export const eighthSnakeTailStainColorRightDirection = "#ffdcb5"; // I1
export const eighthSnakeTailStainColorLeftDirection = "#ffc29b"; // I2
export const eighthSnakeTailStainColorTopDirection = "#ffb28b"; // I3
export const eighthSnakeTailStainColorBottomDirection = "#ffa27b"; // I4
export const eighthSnakeBorderColor = "#f3825b"; // I6
export const eighthSnakeStainBorderColor = "#c3522b"; //  I9

export const ninthSnakeHeadColor = "#ce9c7b"; // J5
export const ninthSnakeEyePrimaryColor = "#ce9c7b"; // J5
export const ninthSnakeEyeSecondaryColor = "#f1f2f6";
export const ninthSnakeEyeTertiaryColor = "#5e2c0b"; // J12
export const ninthSnakeNostrilColor = "#5e2c0b"; // J12
export const ninthSnakeBodyColor = "#ae7c5b"; // J7
export const ninthSnakeLongStainColor = "#ce9c7b"; // J5
export const ninthSnakeRoundStainColor = "#be8c6b"; // J6
export const ninthSnakeTailColor = "#ce9c7b"; // J5
export const ninthSnakeTailStainColorRightDirection = "#f6c4a3"; // J1
export const ninthSnakeTailStainColorLeftDirection = "#eab897"; // J2
export const ninthSnakeTailStainColorTopDirection = "#dfad8c"; // J3
export const ninthSnakeTailStainColorBottomDirection = "#d4a281"; // J4
export const ninthSnakeBorderColor = "#be8c6b"; // J6
export const ninthSnakeStainBorderColor = "#8e5c3b"; // J9

export const tenthSnakeHeadColor = "#909090"; // M5
export const tenthSnakeEyePrimaryColor = "#909090"; // M5
export const tenthSnakeEyeSecondaryColor = "#f1f2f6";
export const tenthSnakeEyeTertiaryColor = "#000"; // M12
export const tenthSnakeNostrilColor = "#000"; // M12
export const tenthSnakeBodyColor = "#707070"; // M7
export const tenthSnakeLongStainColor = "#909090"; // M5
export const tenthSnakeRoundStainColor = "#808080"; // M6
export const tenthSnakeTailColor = "#909090"; // M5
export const tenthSnakeTailStainColorRightDirection = "#e0e0e0"; // M1
export const tenthSnakeTailStainColorLeftDirection = "#d0d0d0"; // M2
export const tenthSnakeTailStainColorTopDirection = "#c0c0c0"; // M3
export const tenthSnakeTailStainColorBottomDirection = "#a0a0a0"; // M4
export const tenthSnakeBorderColor = "#808080"; // M6
export const tenthSnakeStainBorderColor = "#505050"; // M9
