import {
  imgForest,
  imgRiver,
  imgVolcano,
  imgArctic,
  imgDesert,
  imgLove,
  imgNight,
  imgDay,
  imgCountry,
  imgCity,
  imgCave,
  imgSky,
  greenLightLand,
  greenDarkLand,
  greenBorderLand,
  blueLightLand,
  blueDarkLand,
  blueBorderLand,
  redLightLand,
  redDarkLand,
  redBorderLand,
  turquoiseLightLand,
  turquoiseDarkLand,
  turquoiseBorderLand,
  yellowLightLand,
  yellowDarkLand,
  yellowBorderLand,
  pinkLightLand,
  pinkDarkLand,
  pinkBorderLand,
  brownLightLand,
  brownDarkLand,
  brownBorderLand,
  grayLightLand,
  grayDarkLand,
  grayBorderLand,
  purpleLightLand,
  purpleDarkLand,
  purpleBorderLand,
  orangeLightLand,
  orangeDarkLand,
  orangeBorderLand,
  blackLightLand,
  blackDarkLand,
  blackBorderLand,
  whiteLightLand,
  whiteDarkLand,
  whiteBorderLand,
} from "../index.js";

export const arrImgLand = [
  {
    src: imgForest,
    alt: "image forêt",
    height: 35,
    width: 35,
    colorLightLand: greenLightLand,
    colorDarkLand: greenDarkLand,
    colorBorderLand: greenBorderLand,
    name: "forest",
    txt: "La <span>forêt</span> a été selectionnée.",
  },
  {
    src: imgRiver,
    alt: "image rivière",
    height: 35,
    width: 35,
    colorLightLand: blueLightLand,
    colorDarkLand: blueDarkLand,
    colorBorderLand: blueBorderLand,
    name: "river",
    txt: "La <span>rivière</span> a été selectionnée.",
  },
  {
    src: imgVolcano,
    alt: "image volcan",
    height: 35,
    width: 35,
    colorLightLand: redLightLand,
    colorDarkLand: redDarkLand,
    colorBorderLand: redBorderLand,
    name: "volcano",
    txt: "Le <span>volcan</span> a été selectionné.",
  },
  {
    src: imgArctic,
    alt: "image arctique",
    height: 35,
    width: 35,
    colorLightLand: turquoiseLightLand,
    colorDarkLand: turquoiseDarkLand,
    colorBorderLand: turquoiseBorderLand,
    name: "arctic",
    txt: "L'<span>arctique</span> a été selectionnée.",
  },
  {
    src: imgDesert,
    alt: "image désert",
    height: 35,
    width: 35,
    colorLightLand: yellowLightLand,
    colorDarkLand: yellowDarkLand,
    colorBorderLand: yellowBorderLand,
    name: "desert",
    txt: "Le <span>désert</span> a été selectionné.",
  },
  {
    src: imgLove,
    alt: "image romantique",
    height: 35,
    width: 35,
    colorLightLand: pinkLightLand,
    colorDarkLand: pinkDarkLand,
    colorBorderLand: pinkBorderLand,
    name: "love",
    txt: "Le <span>romantique</span> a été selectionné.",
  },
  {
    src: imgCountry,
    alt: "image campagne",
    height: 35,
    width: 35,
    colorLightLand: brownLightLand,
    colorDarkLand: brownDarkLand,
    colorBorderLand: brownBorderLand,
    name: "country",
    txt: "La <span>campagne</span> a été selectionnée.",
  },
  {
    src: imgCity,
    alt: "image ville",
    height: 35,
    width: 35,
    colorLightLand: grayLightLand,
    colorDarkLand: grayDarkLand,
    colorBorderLand: grayBorderLand,
    name: "city",
    txt: "La <span>ville</span> a été selectionnée.",
  },
  {
    src: imgNight,
    alt: "image nuit",
    height: 35,
    width: 35,
    colorLightLand: purpleLightLand,
    colorDarkLand: purpleDarkLand,
    colorBorderLand: purpleBorderLand,
    name: "night",
    txt: "La <span>nuit</span> a été selectionnée.",
  },
  {
    src: imgDay,
    alt: "image jour",
    height: 35,
    width: 35,
    colorLightLand: orangeLightLand,
    colorDarkLand: orangeDarkLand,
    colorBorderLand: orangeBorderLand,
    name: "day",
    txt: "Le <span>jour</span> a été selectionné.",
  },
  {
    src: imgCave,
    alt: "image grotte",
    height: 35,
    width: 35,
    colorLightLand: blackLightLand,
    colorDarkLand: blackDarkLand,
    colorBorderLand: blackBorderLand,
    name: "cave",
    txt: "La <span>grotte</span> a été selectionnée.",
  },
  {
    src: imgSky,
    alt: "image ciel",
    height: 35,
    width: 35,
    colorLightLand: whiteLightLand,
    colorDarkLand: whiteDarkLand,
    colorBorderLand: whiteBorderLand,
    name: "sky",
    txt: "Le <span>ciel</span> a été selectionné.",
  },
];
