import {
  imgApple,
  imgPear,
  imgBlueberry,
  imgPlum,
  imgBanana,
  imgPeach,
  imgCoconut,
  imgWatermelon,
  imgGrape,
  imgOrange,
  imgBlackberry,
  imgDragon,
} from "../index.js";

export const arrImgFruit = [
  {
    src: imgApple,
    alt: "image pomme",
    height: 40,
    width: 40,
    left: 155,
    name: "apple",
    txt: "La <span>pomme</span> a été selectionnée.",
  },
  {
    src: imgPear,
    alt: "image poire",
    height: 40,
    width: 40,
    left: 115,
    name: "pear",
    txt: "La <span>poire</span> a été selectionnée.",
  },
  {
    src: imgBlueberry,
    alt: "image myrtille",
    height: 40,
    width: 40,
    left: 75,
    name: "blueberry",
    txt: "La <span>myrtille</span> a été selectionnée.",
  },
  {
    src: imgPlum,
    alt: "image prune",
    height: 40,
    width: 40,
    left: 35,
    name: "plum",
    txt: "La <span>prune</span> a été selectionnée.",
  },
  {
    src: imgBanana,
    alt: "image banane",
    height: 40,
    width: 40,
    left: -5,
    name: "banana",
    txt: "La <span>banane</span> a été selectionnée.",
  },
  {
    src: imgPeach,
    alt: "image pêche",
    height: 40,
    width: 40,
    left: -45,
    name: "peach",
    txt: "La <span>pêche</span> a été selectionnée.",
  },
  {
    src: imgCoconut,
    alt: "image coco",
    height: 40,
    width: 40,
    left: -85,
    name: "coconut",
    txt: "La noix de <span>coco</span> a été selectionnée.",
  },
  {
    src: imgWatermelon,
    alt: "image pastèque",
    height: 40,
    width: 40,
    left: -125,
    name: "watermelon",
    txt: "La <span>pastèque</span> a été selectionnée.",
  },
  {
    src: imgGrape,
    alt: "image raisin",
    height: 40,
    width: 40,
    left: -165,
    name: "grape",
    txt: "La grappe de <span>raisin</span> a été selectionnée.",
  },
  {
    src: imgOrange,
    alt: "image orange",
    height: 40,
    width: 40,
    left: -205,
    name: "orange",
    txt: "L'<span>orange</span> a été selectionnée.",
  },
  {
    src: imgBlackberry,
    alt: "image mûre",
    height: 40,
    width: 40,
    left: -245,
    name: "blackberry",
    txt: "La <span>mûre</span> a été selectionnée.",
  },
  {
    src: imgDragon,
    alt: "image dragon",
    height: 40,
    width: 40,
    left: -285,
    name: "dragon",
    txt: "Le fruit du <span>dragon</span> a été selectionnée.",
  },
];
