export const data = {
  isMenuOpen: true,
  isGamePlay: false,
  keyPress: false,
  isBtnParamActive: false,
  isTabOptionActive: true,
  isTabDetailActive: false,
  isTabRuleActive: false,
  isTabCommandActive: false,
  fruit: "apple",
  snake: "blue",
  land: "forest",
  move: "normal",
  mode: "close",
  screen: "tablet",
  direction: "east",
  speed: 700,
  number: 0,
  xyFruit: [12, 7],
  xySnake: [
    [2, 7],
    [1, 7],
    [0, 7],
  ],
};
